#!/bin/sh
# SVCID PERF: 10 ms
# Load Plugin Functions

function getConfigValue {
	if [ ! -f $BARTLBY_CONFIG ];
	then
		echo "Config $BARTLBY_CONFIG doesnt look like a file"  3
		exit;
	fi;
	
	r=`cat $BARTLBY_CONFIG |grep $1|awk -F"=" '{print \$2}'`
	echo $r;

}


RRD_HTDOCS=$(getConfigValue performance_rrd_htdocs|tr -d [:blank:]);

RRD_TOOLCFG=$(getConfigValue rrd_tool|tr -d [:blank:]);
RRDTOOL=${RRD_TOOLCFG:-'/usr/bin/rrdtool'}

#3188_bartlby_http_192.168.2.228_hrProcessorLoad.3.rrd
RRDFILE="${RRD_HTDOCS}/${1}_bartlby_http.rrd";

PNGFILE="${RRDFILE}.png";
PNGFILE_SEVEN="${RRDFILE}7.png";


RRD_VALUE=$3;

if [ ! -f $RRDFILE ];
then
	if [ "x${BARTLBY_HOME}" != "x" ];
	then
		ORIGFILE="${BARTLBY_HOME}/perf/defaults/bartlby_http.rrd.xml";
		if [ -f $ORIGFILE ];
		then
			$RRDTOOL restore $ORIGFILE $RRDFILE;
			chmod a+rw $RRDFILE;
		fi;
	else
		echo "BARTLBY_HOME not set maybe you are running from command line";
		exit;
	fi;
fi;



if [ "$1" = "graph" ];
then
	#3188_bartlby_http_192.168.2.228_hrProcessorLoad.3.rrd
	RRDFILE="${RRD_HTDOCS}/${2}_bartlby_http.rrd";

	PNGFILE="${RRDFILE}.png";
	PNGFILE_SEVEN="${RRDFILE}7.png";

	PNGFILE_MONTH="${RRDFILE}31.png";

	PNGFILE_YEAR="${RRDFILE}365.png";
	PNGFILE_HOUR="${RRDFILE}60m.png";

        nice -n19 $RRDTOOL graph $PNGFILE_HOUR \
           -t "bartlby http response time ($BARTLBY_CURR_HOST / $BARTLBY_CURR_SERVICE)  @ $(/bin/date "+%d.%m.%Y %H:%M:%S")" -v "Time in ms" \
           --start -1hour \
           --height="300" \
           --width="600" \
           -c "BACK#ffffff" \
           -c "SHADEA#ffffff" \
           -c "SHADEB#ffffff" \
           -c "FONT#000000" \
           -c "CANVAS#ffffff" \
           -c "GRID#666666" \
           -c "MGRID#AAAAAA" \
           -c "FRAME#202020" \
           -c "ARROW#000000" \
           "DEF:ping_time=${RRDFILE}:ping:AVERAGE" \
           "CDEF:shading2=ping_time,0.98,*" "AREA:shading2#F90000:$BARTLBY_CURR_SERVICE" \
           "GPRINT:ping_time:LAST:Last\: %5.2lf ms" \
           "GPRINT:ping_time:MIN:Min\: %5.2lf ms" \
           "GPRINT:ping_time:MAX:Max\: %5.2lf ms" \
           "GPRINT:ping_time:AVERAGE:Avg\: %5.2lf ms" \
           "CDEF:shading10=ping_time,0.90,*" "AREA:shading10#E10000" \
           "CDEF:shading15=ping_time,0.85,*" "AREA:shading15#D20000" \
           "CDEF:shading20=ping_time,0.80,*" "AREA:shading20#C30000" \
           "CDEF:shading25=ping_time,0.75,*" "AREA:shading25#B40000" \
           "CDEF:shading30=ping_time,0.70,*" "AREA:shading30#A50000" \
           "CDEF:shading35=ping_time,0.65,*" "AREA:shading35#960000" \
           "CDEF:shading40=ping_time,0.60,*" "AREA:shading40#870000" \
           "CDEF:shading45=ping_time,0.55,*" "AREA:shading45#780000" \
           "CDEF:shading50=ping_time,0.50,*" "AREA:shading50#690000" \
           "CDEF:shading55=ping_time,0.45,*" "AREA:shading55#5A0000" \
           "CDEF:shading60=ping_time,0.40,*" "AREA:shading60#4B0000" \
           "CDEF:shading65=ping_time,0.35,*" "AREA:shading65#3C0000" \
           "CDEF:shading70=ping_time,0.30,*" "AREA:shading70#2D0000" \
           "CDEF:shading75=ping_time,0.25,*" "AREA:shading75#180000" \
           "CDEF:shading80=ping_time,0.20,*" "AREA:shading80#0F0000" \
           "CDEF:shading85=ping_time,0.15,*" "AREA:shading85#000000" >/dev/null
        echo "generated 24 hour graph";

	nice -n19 $RRDTOOL graph $PNGFILE_YEAR \
           -t "bartlby http response time ($BARTLBY_CURR_HOST / $BARTLBY_CURR_SERVICE)  @ $(/bin/date "+%d.%m.%Y %H:%M:%S")" -v "Time in ms" \
           --start -1year \
           --height="300" \
           --width="600" \
           -c "BACK#ffffff" \
           -c "SHADEA#ffffff" \
           -c "SHADEB#ffffff" \
           -c "FONT#000000" \
           -c "CANVAS#ffffff" \
           -c "GRID#666666" \
           -c "MGRID#AAAAAA" \
           -c "FRAME#202020" \
           -c "ARROW#000000" \
           "DEF:ping_time=${RRDFILE}:ping:AVERAGE" \
           "CDEF:shading2=ping_time,0.98,*" "AREA:shading2#F90000:$BARTLBY_CURR_SERVICE" \
           "GPRINT:ping_time:LAST:Last\: %5.2lf ms" \
           "GPRINT:ping_time:MIN:Min\: %5.2lf ms" \
           "GPRINT:ping_time:MAX:Max\: %5.2lf ms" \
           "GPRINT:ping_time:AVERAGE:Avg\: %5.2lf ms" \
           "CDEF:shading10=ping_time,0.90,*" "AREA:shading10#E10000" \
           "CDEF:shading15=ping_time,0.85,*" "AREA:shading15#D20000" \
           "CDEF:shading20=ping_time,0.80,*" "AREA:shading20#C30000" \
           "CDEF:shading25=ping_time,0.75,*" "AREA:shading25#B40000" \
           "CDEF:shading30=ping_time,0.70,*" "AREA:shading30#A50000" \
           "CDEF:shading35=ping_time,0.65,*" "AREA:shading35#960000" \
           "CDEF:shading40=ping_time,0.60,*" "AREA:shading40#870000" \
           "CDEF:shading45=ping_time,0.55,*" "AREA:shading45#780000" \
           "CDEF:shading50=ping_time,0.50,*" "AREA:shading50#690000" \
           "CDEF:shading55=ping_time,0.45,*" "AREA:shading55#5A0000" \
           "CDEF:shading60=ping_time,0.40,*" "AREA:shading60#4B0000" \
           "CDEF:shading65=ping_time,0.35,*" "AREA:shading65#3C0000" \
           "CDEF:shading70=ping_time,0.30,*" "AREA:shading70#2D0000" \
           "CDEF:shading75=ping_time,0.25,*" "AREA:shading75#180000" \
           "CDEF:shading80=ping_time,0.20,*" "AREA:shading80#0F0000" \
           "CDEF:shading85=ping_time,0.15,*" "AREA:shading85#000000" >/dev/null
        echo "generated 24 hour graph";


	nice -n19 $RRDTOOL graph $PNGFILE_MONTH \
           -t "bartlby http response time ($BARTLBY_CURR_HOST / $BARTLBY_CURR_SERVICE)  @ $(/bin/date "+%d.%m.%Y %H:%M:%S")" -v "Time in ms" \
           --start -1month \
           --height="300" \
           --width="600" \
           -c "BACK#ffffff" \
           -c "SHADEA#ffffff" \
           -c "SHADEB#ffffff" \
           -c "FONT#000000" \
           -c "CANVAS#ffffff" \
           -c "GRID#666666" \
           -c "MGRID#AAAAAA" \
           -c "FRAME#202020" \
           -c "ARROW#000000" \
           "DEF:ping_time=${RRDFILE}:ping:AVERAGE" \
           "CDEF:shading2=ping_time,0.98,*" "AREA:shading2#F90000:$BARTLBY_CURR_SERVICE" \
           "GPRINT:ping_time:LAST:Last\: %5.2lf ms" \
           "GPRINT:ping_time:MIN:Min\: %5.2lf ms" \
           "GPRINT:ping_time:MAX:Max\: %5.2lf ms" \
           "GPRINT:ping_time:AVERAGE:Avg\: %5.2lf ms" \
           "CDEF:shading10=ping_time,0.90,*" "AREA:shading10#E10000" \
           "CDEF:shading15=ping_time,0.85,*" "AREA:shading15#D20000" \
           "CDEF:shading20=ping_time,0.80,*" "AREA:shading20#C30000" \
           "CDEF:shading25=ping_time,0.75,*" "AREA:shading25#B40000" \
           "CDEF:shading30=ping_time,0.70,*" "AREA:shading30#A50000" \
           "CDEF:shading35=ping_time,0.65,*" "AREA:shading35#960000" \
           "CDEF:shading40=ping_time,0.60,*" "AREA:shading40#870000" \
           "CDEF:shading45=ping_time,0.55,*" "AREA:shading45#780000" \
           "CDEF:shading50=ping_time,0.50,*" "AREA:shading50#690000" \
           "CDEF:shading55=ping_time,0.45,*" "AREA:shading55#5A0000" \
           "CDEF:shading60=ping_time,0.40,*" "AREA:shading60#4B0000" \
           "CDEF:shading65=ping_time,0.35,*" "AREA:shading65#3C0000" \
           "CDEF:shading70=ping_time,0.30,*" "AREA:shading70#2D0000" \
           "CDEF:shading75=ping_time,0.25,*" "AREA:shading75#180000" \
           "CDEF:shading80=ping_time,0.20,*" "AREA:shading80#0F0000" \
           "CDEF:shading85=ping_time,0.15,*" "AREA:shading85#000000" >/dev/null
        echo "generated 24 hour graph";

	

	nice -n19 $RRDTOOL graph $PNGFILE \
     	   -t "bartlby http response time ($BARTLBY_CURR_HOST / $BARTLBY_CURR_SERVICE)  @ $(/bin/date "+%d.%m.%Y %H:%M:%S")" -v "Time in ms" \
     	   --start -86400 \
     	   --height="300" \
     	   --width="600" \
     	   -c "BACK#ffffff" \
     	   -c "SHADEA#ffffff" \
     	   -c "SHADEB#ffffff" \
     	   -c "FONT#000000" \
     	   -c "CANVAS#ffffff" \
     	   -c "GRID#666666" \
     	   -c "MGRID#AAAAAA" \
     	   -c "FRAME#202020" \
     	   -c "ARROW#000000" \
     	   "DEF:ping_time=${RRDFILE}:ping:AVERAGE" \
     	   "CDEF:shading2=ping_time,0.98,*" "AREA:shading2#F90000:$BARTLBY_CURR_SERVICE" \
     	   "GPRINT:ping_time:LAST:Last\: %5.2lf ms" \
     	   "GPRINT:ping_time:MIN:Min\: %5.2lf ms" \
     	   "GPRINT:ping_time:MAX:Max\: %5.2lf ms" \
     	   "GPRINT:ping_time:AVERAGE:Avg\: %5.2lf ms" \
     	   "CDEF:shading10=ping_time,0.90,*" "AREA:shading10#E10000" \
     	   "CDEF:shading15=ping_time,0.85,*" "AREA:shading15#D20000" \
     	   "CDEF:shading20=ping_time,0.80,*" "AREA:shading20#C30000" \
     	   "CDEF:shading25=ping_time,0.75,*" "AREA:shading25#B40000" \
     	   "CDEF:shading30=ping_time,0.70,*" "AREA:shading30#A50000" \
     	   "CDEF:shading35=ping_time,0.65,*" "AREA:shading35#960000" \
     	   "CDEF:shading40=ping_time,0.60,*" "AREA:shading40#870000" \
     	   "CDEF:shading45=ping_time,0.55,*" "AREA:shading45#780000" \
     	   "CDEF:shading50=ping_time,0.50,*" "AREA:shading50#690000" \
     	   "CDEF:shading55=ping_time,0.45,*" "AREA:shading55#5A0000" \
     	   "CDEF:shading60=ping_time,0.40,*" "AREA:shading60#4B0000" \
     	   "CDEF:shading65=ping_time,0.35,*" "AREA:shading65#3C0000" \
     	   "CDEF:shading70=ping_time,0.30,*" "AREA:shading70#2D0000" \
     	   "CDEF:shading75=ping_time,0.25,*" "AREA:shading75#180000" \
     	   "CDEF:shading80=ping_time,0.20,*" "AREA:shading80#0F0000" \
     	   "CDEF:shading85=ping_time,0.15,*" "AREA:shading85#000000" >/dev/null
	echo "generated 24 hour graph";

	nice -n19 $RRDTOOL graph $PNGFILE_SEVEN \
	        -t "bartlby http response time ($BARTLBY_CURR_HOST / $BARTLBY_CURR_SERVICE)  @ $(/bin/date "+%d.%m.%Y %H:%M:%S")" -v "Time in ms" \
	        --start -604800 \
	        --height="300" \
	        --width="600" \
	        -c "BACK#ffffff" \
	        -c "SHADEA#ffffff" \
	        -c "SHADEB#ffffff" \
	        -c "FONT#000000" \
	        -c "CANVAS#ffffff" \
	        -c "GRID#666666" \
	        -c "MGRID#AAAAAA" \
	        -c "FRAME#202020" \
	        -c "ARROW#000000" \
	        "DEF:ping_time=${RRDFILE}:ping:AVERAGE" \
	        "CDEF:shading2=ping_time,0.98,*" "AREA:shading2#F90000:$BARTLBY_CURR_SERVICE" \
	        "GPRINT:ping_time:LAST:Last\: %5.2lf ms" \
	        "GPRINT:ping_time:MIN:Min\: %5.2lf ms" \
	        "GPRINT:ping_time:MAX:Max\: %5.2lf ms" \
	        "GPRINT:ping_time:AVERAGE:Avg\: %5.2lf ms" \
	        "CDEF:shading10=ping_time,0.90,*" "AREA:shading10#E10000" \
	        "CDEF:shading15=ping_time,0.85,*" "AREA:shading15#D20000" \
	        "CDEF:shading20=ping_time,0.80,*" "AREA:shading20#C30000" \
	        "CDEF:shading25=ping_time,0.75,*" "AREA:shading25#B40000" \
	        "CDEF:shading30=ping_time,0.70,*" "AREA:shading30#A50000" \
	        "CDEF:shading35=ping_time,0.65,*" "AREA:shading35#960000" \
	        "CDEF:shading40=ping_time,0.60,*" "AREA:shading40#870000" \
	        "CDEF:shading45=ping_time,0.55,*" "AREA:shading45#780000" \
	        "CDEF:shading50=ping_time,0.50,*" "AREA:shading50#690000" \
	        "CDEF:shading55=ping_time,0.45,*" "AREA:shading55#5A0000" \
	        "CDEF:shading60=ping_time,0.40,*" "AREA:shading60#4B0000" \
	        "CDEF:shading65=ping_time,0.35,*" "AREA:shading65#3C0000" \
	        "CDEF:shading70=ping_time,0.30,*" "AREA:shading70#2D0000" \
	        "CDEF:shading75=ping_time,0.25,*" "AREA:shading75#180000" \
	        "CDEF:shading80=ping_time,0.20,*" "AREA:shading80#0F0000" \
	        "CDEF:shading85=ping_time,0.15,*" "AREA:shading85#000000" >/dev/null
	
	
	echo "generated 7day graph";
	
	#--start -604800
else
	nice -n19 $RRDTOOL update $RRDFILE N:$RRD_VALUE
	

fi;


