#!/bin/sh
#2559 PERF: DOWN UP last
# Load Plugin Functions

function getConfigValue {
	if [ ! -f $BARTLBY_CONFIG ];
	then
		echo "Config $BARTLBY_CONFIG doesnt look like a file"  3
		exit;
	fi;
	
	r=`cat $BARTLBY_CONFIG |grep $1|awk -F"=" '{print \$2}'`
	echo $r;

}


RRD_HTDOCS=$(getConfigValue performance_rrd_htdocs|tr -d [:blank:]);

RRD_TOOLCFG=$(getConfigValue rrd_tool|tr -d [:blank:]);
RRDTOOL=${RRD_TOOLCFG:-'/usr/bin/rrdtool'}

RRDFILE="${RRD_HTDOCS}/${1}_bartlby_if.rrd";

PNGFILE="${RRD_HTDOCS}/${1}_bartlby_if.png";
PNGFILE_SEVEN="${RRD_HTDOCS}/${1}_bartlby_if7.png";
PNGFILE_MONTH="${RRD_HTDOCS}/${1}_bartlby_if31.png";
PNGFILE_YEAR="${RRD_HTDOCS}/${1}_bartlby_if365.png";

#Check if RRD file is existing

if [ ! -f $RRDFILE ];
then
	if [ "x${BARTLBY_HOME}" != "x" ];
	then
		ORIGFILE="${BARTLBY_HOME}/perf/defaults/bartlby_if.rrd.xml";
		if [ -f $ORIGFILE ];
		then
			$RRDTOOL restore $ORIGFILE $RRDFILE;
			chmod a+rw $RRDFILE;
		fi;
	else
		echo "BARTLBY_HOME not set maybe you are running from command line";
		exit;
	fi;
fi;





if [ "$1" = "graph" ];
then
	RRDFILE="${RRD_HTDOCS}/${2}_bartlby_if.rrd";

	PNGFILE="${RRD_HTDOCS}/${2}_bartlby_if.png";
	PNGFILE_SEVEN="${RRD_HTDOCS}/${2}_bartlby_if7.png";
	PNGFILE_MONTH="${RRD_HTDOCS}/${2}_bartlby_if31.png";

	PNGFILE_YEAR="${RRD_HTDOCS}/${2}_bartlby_if365.png";
	PNGFILE_HOUR="${RRD_HTDOCS}/${2}_bartlby_if24h.png";


	   $RRDTOOL graph $PNGFILE_HOUR --start -1hour  -w 600 -h 300 \
                DEF:inoctets=${RRDFILE}:input:AVERAGE \
                DEF:outoctets=${RRDFILE}:output:AVERAGE \
                'CDEF:inbits=inoctets,8,*' \
                'CDEF:outbits=outoctets,8,*' \
                'GPRINT:outbits:LAST:Last %.3lf %sbytes Out\j' \
                'GPRINT:inbits:LAST:Last %.3lf %sbytes In\j' \
                'GPRINT:outbits:AVERAGE:AVG %.3lf %sbytes Out\j' \
                'GPRINT:inbits:AVERAGE:AVG %.3lf %sbytes In\j' \
                AREA:inbits#00FF00:"In traffic" \
                LINE1:outbits#0000FF:"Out traffic" \


        $RRDTOOL graph $PNGFILE --start -86400  -w 600 -h 300 \
                DEF:inoctets=${RRDFILE}:input:AVERAGE \
                DEF:outoctets=${RRDFILE}:output:AVERAGE \
                'CDEF:inbits=inoctets,8,*' \
                'CDEF:outbits=outoctets,8,*' \
                'GPRINT:outbits:LAST:Last %.3lf %sbytes Out\j' \
                'GPRINT:inbits:LAST:Last %.3lf %sbytes In\j' \
                'GPRINT:outbits:AVERAGE:AVG %.3lf %sbytes Out\j' \
                'GPRINT:inbits:AVERAGE:AVG %.3lf %sbytes In\j' \
                AREA:inbits#00FF00:"In traffic" \
                LINE1:outbits#0000FF:"Out traffic" \


        $RRDTOOL graph $PNGFILE_SEVEN --start -1week  -w 600 -h 300 \
                DEF:inoctets=${RRDFILE}:input:AVERAGE \
                DEF:outoctets=${RRDFILE}:output:AVERAGE \
                'CDEF:inbits=inoctets,8,*' \
                'CDEF:outbits=outoctets,8,*' \
                'GPRINT:outbits:LAST:Last %.3lf %sbytes Out\j' \
                'GPRINT:inbits:LAST:Last %.3lf %sbytes In\j' \
                'GPRINT:outbits:AVERAGE:AVG %.3lf %sbytes Out\j' \
                'GPRINT:inbits:AVERAGE:AVG %.3lf %sbytes In\j' \
                AREA:inbits#00FF00:"In traffic" \
                LINE1:outbits#0000FF:"Out traffic" \


        $RRDTOOL graph $PNGFILE_MONTH --start -1month  -w 600 -h 300 \
                DEF:inoctets=${RRDFILE}:input:AVERAGE \
                DEF:outoctets=${RRDFILE}:output:AVERAGE \
                'CDEF:inbits=inoctets,8,*' \
                'CDEF:outbits=outoctets,8,*' \
                'GPRINT:outbits:LAST:Last %.3lf %sbytes Out\j' \
                'GPRINT:inbits:LAST:Last %.3lf %sbytes In\j' \
                'GPRINT:outbits:AVERAGE:AVG %.3lf %sbytes Out\j' \
                'GPRINT:inbits:AVERAGE:AVG %.3lf %sbytes In\j' \
                AREA:inbits#00FF00:"In traffic" \
                LINE1:outbits#0000FF:"Out traffic" \


        $RRDTOOL graph $PNGFILE_YEAR --start -1year  -w 600 -h 300 \
                DEF:inoctets=${RRDFILE}:input:AVERAGE \
                DEF:outoctets=${RRDFILE}:output:AVERAGE \
                'CDEF:inbits=inoctets,8,*' \
                'CDEF:outbits=outoctets,8,*' \
                'GPRINT:outbits:LAST:Last %.3lf %sbytes Out\j' \
                'GPRINT:inbits:LAST:Last %.3lf %sbytes In\j' \
                'GPRINT:outbits:AVERAGE:AVG %.3lf %sbytes Out\j' \
                'GPRINT:inbits:AVERAGE:AVG %.3lf %sbytes In\j' \
                AREA:inbits#00FF00:"In traffic" \
                LINE1:outbits#0000FF:"Out traffic" \


else
	D=$3
	U=$4
	nice -n19 $RRDTOOL update $RRDFILE N:$D:$U
fi;


