#!/bin/sh
#2559 PERF: COUNT last
# Load Plugin Functions

function getConfigValue {
	if [ ! -f $BARTLBY_CONFIG ];
	then
		echo "Config $BARTLBY_CONFIG doesnt look like a file"  3
		exit;
	fi;
	
	r=`cat $BARTLBY_CONFIG |grep $1|awk -F"=" '{print \$2}'`
	echo $r;

}


RRD_HTDOCS=$(getConfigValue performance_rrd_htdocs|tr -d [:blank:]);

RRD_TOOLCFG=$(getConfigValue rrd_tool|tr -d [:blank:]);
RRDTOOL=${RRD_TOOLCFG:-'/usr/bin/rrdtool'}

RRDFILE="${RRD_HTDOCS}/${1}_bartlby_files_in_dir.rrd";

PNGFILE="${RRD_HTDOCS}/${1}_bartlby_files_in_dir.png";
PNGFILE_SEVEN="${RRD_HTDOCS}/${1}_bartlby_files_in_dir7.png";
PNGFILE_MONTH="${RRD_HTDOCS}/${1}_bartlby_files_in_dir31.png";
PNGFILE_YEAR="${RRD_HTDOCS}/${1}_bartlby_files_in_dir365.png";

#Check if RRD file is existing

if [ ! -f $RRDFILE ];
then
	if [ "x${BARTLBY_HOME}" != "x" ];
	then
		ORIGFILE="${BARTLBY_HOME}/perf/defaults/bartlby_files_in_dir.rrd.xml";
		if [ -f $ORIGFILE ];
		then
			$RRDTOOL restore $ORIGFILE $RRDFILE;
			chmod a+rw $RRDFILE;
		fi;
	else
		echo "BARTLBY_HOME not set maybe you are running from command line";
		exit;
	fi;
fi;





if [ "$1" = "graph" ];
then
	RRDFILE="${RRD_HTDOCS}/${2}_bartlby_files_in_dir.rrd";

	PNGFILE="${RRD_HTDOCS}/${2}_bartlby_files_in_dir.png";
	PNGFILE_SEVEN="${RRD_HTDOCS}/${2}_bartlby_files_in_dir7.png";
	PNGFILE_MONTH="${RRD_HTDOCS}/${2}_bartlby_files_in_dir31.png";

	PNGFILE_YEAR="${RRD_HTDOCS}/${2}_bartlby_files_in_dir365.png";
	PNGFILE_HOUR="${RRD_HTDOCS}/${2}_bartlby_files_in_dir24h.png";

	
	$RRDTOOL graph $PNGFILE --start -1day -a PNG --vertical-label "File count" -w 600 -h 300 DEF:auswertung=${RRDFILE}:processes:AVERAGE LINE1:auswertung#ff0000:"File counter" VDEF:auswertung1=auswertung,AVERAGE DEF:maxaus=${RRDFILE}:processes:MAX VDEF:maxaus1=maxaus,MAXIMUM
	$RRDTOOL graph $PNGFILE_SEVEN --start -1week -a PNG --vertical-label "File count" -w 600 -h 300 DEF:auswertung=${RRDFILE}:processes:AVERAGE LINE1:auswertung#ff0000:"File counter" VDEF:auswertung1=auswertung,AVERAGE DEF:maxaus=${RRDFILE}:processes:MAX VDEF:maxaus1=maxaus,MAXIMUM
	$RRDTOOL graph $PNGFILE_MONTH --start -1month -a PNG --vertical-label "File count" -w 600 -h 300 DEF:auswertung=${RRDFILE}:processes:AVERAGE LINE1:auswertung#ff0000:"File counter" VDEF:auswertung1=auswertung,AVERAGE DEF:maxaus=${RRDFILE}:processes:MAX VDEF:maxaus1=maxaus,MAXIMUM
	$RRDTOOL graph $PNGFILE_YEAR --start -1year -a PNG --vertical-label "File count" -w 600 -h 300 DEF:auswertung=${RRDFILE}:processes:AVERAGE LINE1:auswertung#ff0000:"File counter" VDEF:auswertung1=auswertung,AVERAGE DEF:maxaus=${RRDFILE}:processes:MAX VDEF:maxaus1=maxaus,MAXIMUM
	$RRDTOOL graph $PNGFILE_HOUR --start -1hour -a PNG --vertical-label "File count" -w 600 -h 300 DEF:auswertung=${RRDFILE}:processes:AVERAGE LINE1:auswertung#ff0000:"File counter" VDEF:auswertung1=auswertung,AVERAGE DEF:maxaus=${RRDFILE}:processes:MAX VDEF:maxaus1=maxaus,MAXIMUM
	echo "done";


else
	D=$3
	nice -n19 $RRDTOOL update $RRDFILE N:$D
fi;


