#!/bin/sh
#2559 PERF: 0.54 0.64 0.65
# Load Plugin Functions

function getConfigValue {
	if [ ! -f $BARTLBY_CONFIG ];
	then
		echo "Config $BARTLBY_CONFIG doesnt look like a file"  3
		exit;
	fi;
	
	r=`cat $BARTLBY_CONFIG |grep $1|awk -F"=" '{print \$2}'`
	echo $r;

}


RRD_HTDOCS=$(getConfigValue performance_rrd_htdocs|tr -d [:blank:]);

RRD_TOOLCFG=$(getConfigValue rrd_tool|tr -d [:blank:]);
RRDTOOL=${RRD_TOOLCFG:-'nice -n19 /usr/bin/rrdtool'}

RRDFILE="${RRD_HTDOCS}/${1}_bartlby_load.rrd";
PNGFILE="${RRD_HTDOCS}/${1}_bartlby_load.png";
PNGFILE_SEVEN="${RRD_HTDOCS}/${1}_bartlby_load7.png";
PNGFILE_MONTH="${RRD_HTDOCS}/${1}_bartlby_load31.png";
PNGFILE_YEAR="${RRD_HTDOCS}/${1}_bartlby_load365.png";

if [ ! -f $RRDFILE ];
then
	if [ "x${BARTLBY_HOME}" != "x" ];
	then
		ORIGFILE="${BARTLBY_HOME}/perf/defaults/bartlby_load.rrd.xml";
		if [ -f $ORIGFILE ];
		then
			$RRDTOOL restore $ORIGFILE $RRDFILE;
			chmod a+rw $RRDFILE;
		fi;
	else
		echo "BARTLBY_HOME not set maybe you are running from command line";
		exit;
	fi;
fi;



if [ "$1" = "graph" ];
then
	RRDFILE="${RRD_HTDOCS}/${2}_bartlby_load.rrd";
	PNGFILE="${RRD_HTDOCS}/${2}_bartlby_load.png";
	PNGFILE_SEVEN="${RRD_HTDOCS}/${2}_bartlby_load7.png";
	PNGFILE_MONTH="${RRD_HTDOCS}/${2}_bartlby_load31.png";

	PNGFILE_YEAR="${RRD_HTDOCS}/${2}_bartlby_load365.png";
	PNGFILE_HOUR="${RRD_HTDOCS}/${2}_bartlby_load24h.png";


	nice -n19 $RRDTOOL graph $PNGFILE_HOUR --start -1hour \
                -a PNG -t "Load Average Last Hour ( $BARTLBY_CURR_HOST / $BARTLBY_CURR_SERVICE )" --vertical-label "Average Load" -w 600 -h 300 -M \
                DEF:load1=${RRDFILE}:load1:AVERAGE \
                DEF:load5=${RRDFILE}:load5:AVERAGE \
                DEF:load15=${RRDFILE}:load15:AVERAGE \
                VDEF:load1l=load1,LAST \
                VDEF:load5l=load5,LAST \
                VDEF:load15l=load15,LAST \
                AREA:load1#ff0000:"1 Minutes,   last\:" GPRINT:load1l:"%5.2lf\n" \
                AREA:load5#ff9900:"5 Minutes,  last\:" GPRINT:load5l:"%5.2lf     generated @ \n" \
                AREA:load15#ffff00:"15 Minutes, last\:" GPRINT:load15l:"%5.2lf    $(/bin/date "+%d.%m.%Y %H\:%M\:%S")" \
                LINE1:load5#ff9900:"" \
                LINE1:load1#ff0000:"" > /dev/null
	echo "generated 60min graph $PNGFILE_HOUR";


	nice -n19 $RRDTOOL graph $PNGFILE --start -86400 \
		-a PNG -t "Load Average Last 24 Hours ( $BARTLBY_CURR_HOST / $BARTLBY_CURR_SERVICE )" --vertical-label "Average Load" -w 600 -h 300 -M \
		DEF:load1=${RRDFILE}:load1:AVERAGE \
		DEF:load5=${RRDFILE}:load5:AVERAGE \
		DEF:load15=${RRDFILE}:load15:AVERAGE \
		VDEF:load1l=load1,LAST \
		VDEF:load5l=load5,LAST \
		VDEF:load15l=load15,LAST \
		AREA:load1#ff0000:"1 Minutes,   last\:" GPRINT:load1l:"%5.2lf\n" \
		AREA:load5#ff9900:"5 Minutes,  last\:" GPRINT:load5l:"%5.2lf     generated @ \n" \
		AREA:load15#ffff00:"15 Minutes, last\:" GPRINT:load15l:"%5.2lf    $(/bin/date "+%d.%m.%Y %H\:%M\:%S")" \
		LINE1:load5#ff9900:"" \
		LINE1:load1#ff0000:"" > /dev/null
	echo "generated 24 hour graph";
	# 7 Tage - Load Average
	nice -n19 $RRDTOOL graph $PNGFILE_SEVEN --start -604800 \
		-a PNG -t "Load Average Last 7 Days ( $BARTLBY_CURR_HOST / $BARTLBY_CURR_SERVICE )" --vertical-label "Average Load" -w 600 -h 300 \
		DEF:load1=${RRDFILE}:load1:AVERAGE \
		DEF:load5=${RRDFILE}:load5:AVERAGE \
		DEF:load15=${RRDFILE}:load15:AVERAGE \
		VDEF:load1l=load1,LAST \
		VDEF:load5l=load5,LAST \
		VDEF:load15l=load15,LAST \
		AREA:load1#ff0000:"1 Minutes,   last\:" GPRINT:load1l:"%5.2lf\n" \
		AREA:load5#ff9900:"5 Minutes,  last\:" GPRINT:load5l:"%5.2lf     Generated @ \n" \
		AREA:load15#ffff00:"15 Minutes, last\:" GPRINT:load15l:"%5.2lf    $(/bin/date "+%d.%m.%Y %H\:%M\:%S")" \
		LINE1:load5#ff9900:"" \
		LINE1:load1#ff0000:"" > /dev/null
	echo "generated 7day graph";
	
	# 31 Tage - Load Average
	nice -n19 $RRDTOOL graph $PNGFILE_MONTH --start -1month \
		-a PNG -t "Load Average Last Month ( $BARTLBY_CURR_HOST / $BARTLBY_CURR_SERVICE )" --vertical-label "Average Load" -w 600 -h 300 \
		DEF:load1=${RRDFILE}:load1:AVERAGE \
		DEF:load5=${RRDFILE}:load5:AVERAGE \
		DEF:load15=${RRDFILE}:load15:AVERAGE \
		VDEF:load1l=load1,LAST \
		VDEF:load5l=load5,LAST \
		VDEF:load15l=load15,LAST \
		AREA:load1#ff0000:"1 Minutes,   last\:" GPRINT:load1l:"%5.2lf\n" \
		AREA:load5#ff9900:"5 Minutes,  last\:" GPRINT:load5l:"%5.2lf     Generated @ \n" \
		AREA:load15#ffff00:"15 Minutes, last\:" GPRINT:load15l:"%5.2lf    $(/bin/date "+%d.%m.%Y %H\:%M\:%S")" \
		LINE1:load5#ff9900:"" \
		LINE1:load1#ff0000:"" > /dev/null
	echo "generated 1month graph";
	
	
	# 1 jahr - Load Average
	nice -n19 $RRDTOOL graph $PNGFILE_YEAR --start -1year \
		-a PNG -t "Load Average over a year ( $BARTLBY_CURR_HOST / $BARTLBY_CURR_SERVICE )" --vertical-label "Average Load" -w 600 -h 300 \
		DEF:load1=${RRDFILE}:load1:AVERAGE \
		DEF:load5=${RRDFILE}:load5:AVERAGE \
		DEF:load15=${RRDFILE}:load15:AVERAGE \
		VDEF:load1l=load1,LAST \
		VDEF:load5l=load5,LAST \
		VDEF:load15l=load15,LAST \
		AREA:load1#ff0000:"1 Minutes,   last\:" GPRINT:load1l:"%5.2lf\n" \
		AREA:load5#ff9900:"5 Minutes,  last\:" GPRINT:load5l:"%5.2lf     Generated @ \n" \
		AREA:load15#ffff00:"15 Minutes, last\:" GPRINT:load15l:"%5.2lf    $(/bin/date "+%d.%m.%Y %H\:%M\:%S")" \
		LINE1:load5#ff9900:"" \
		LINE1:load1#ff0000:"" > /dev/null
	echo "generated 1year graph";
	
else
	nice -n19 $RRDTOOL update $RRDFILE N:$3:$4:$5
fi;


