#!/bin/bash

#
## apt-check
##

APTOUTPUT=`apt-get update 2>&1`
EXITCODE=$?
if [ "$EXITCODE" -ne "0" ]
then
	echo "problem with apt-get update"
	exit 2;
fi

#
# simulate "-s" an upgrade
#

APTOUTPUT=`apt-get -s -u upgrade 2>&1|grep "upgraded,"|awk '{print $1}'`
if [ "$APTOUTPUT" -ne "0" ]
then
	echo "$APTOUTPUT requiring upgrade";
	exit 4; #INFO only
fi


echo "no upgrades required";
exit 0;
