#!/bin/bash

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION=`echo '$Revision: 1.1 $' | sed -e 's/[^0-9.]//g'`



print_usage() {
        echo -e "Check logfile"
	echo -e "* Checks LOGFILE if given pattern is found"
        echo "---------------------Usage-----------------------------------------------"
	echo "-F LogFile Def: /var/log/messages"
	echo "-P Pattern to find (AWK LIKE REGEX)"
	echo "-w WARN if X entries found Def:1"
	echo "-c CRITICAL if X Entries found Def:2"
        echo "-h  Show This Help"
	echo "-------------------------------------------------------------------------"
	
}



#Defs:
CRIT=2;
WARN=1;
FL=/var/log/messages
PATTERN="alex"

while getopts F:P:w:c:h o
do
    	case $o in
	F) FL=$OPTARG;;
	P) PATTERN=$OPTARG;;
	w) WARN=$OPTARG;;
	c) CRIT=$OPTARG;;
        h) print_usage; exit $STATE_UNKOWN;;

        esac


done
####


UTMP=/var/tmp/bartlby_`hostname`_`echo $FL|tr -s "/" "_"`.tmp
if [ -e "$UTMP" ]
then
	t=`cat $UTMP`;
	NM=`echo $t|tr -d [:blank:]`;
else
	echo 1 > $UTMP;
	NM=1;
fi;


STR="cat $FL|sed '1, $NM d'|awk '{if (\$0 ~ /$PATTERN/) {print}}'"
FOUND=`eval $STR|wc -l|tr -d [:blank:]`;

####################################
#
# Update last Line FILE UTMP
####################################
cat $FL|wc -l > $UTMP

#####################################
# ok 
# lets do critical warn check :) 
####################################
if [ $FOUND -ge $CRIT ]
then
	echo "CheckILog($FL/$PATTERN $NM-EOF)[critical] found $FOUND CRIT: $CRIT";
	exit $STATE_CRITICAL;
fi;

if [ $FOUND -ge $WARN ]
then
        echo "CheckILog($FL/$PATTERN Range: $NM-EOF)[warning] found $FOUND WARN: $CRIT";
        exit $STATE_WARNING;
fi;

        echo "CheckILog($FL/$PATTERN range: $NM-EOF)[Ok] found $FOUND";
        exit $STATE_OK;


