#!/bin/bash

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION=`echo '$Revision: 1.1 $' | sed -e 's/[^0-9.]//g'`


print_usage() {
        echo "Check How many files in a Direcotry"
        echo "---------------------Usage-----------------------------------------------"
        echo "-D Directory Def:/usr/local/bannerd/QUEUE";
        echo "-w WARN if greater than N files Def: 20";
        echo "-c CRIT if greater than N files Def: 50";
	echo "-p Perf track";
        echo "-h  Show This Help"
        echo "-------------------------------------------------------------------------"
}

#####


#Defs:
DIRE=/var/tmp
WARN="20";
CRIT="50";
PERFIT="false";

while getopts D:w:c:hp o
do
        case $o in
        D) DIRE=$OPTARG;;
        w) WARN=$OPTARG;;
        c) CRIT=$OPTARG;;
	p) PERFIT="true";;
        h) print_usage; exit $STATE_UNKOWN;;

        esac


done

CHK=`find $DIRE -type f|wc -l|tr -d [:blank:]`;

if [ "$PERFIT" = "true" ];
then
	echo "PERF: $CHK last";
fi;

if [ $CHK -gt $CRIT ];
then
        echo "FilesInDir($DIRE/$CHK) critical `date`";
        exit $STATE_CRITICAL;
fi;


if [ $CHK -gt $WARN ];
then
        echo "FilesInDir($DIRE/$CHK) warning `date`";
        exit $STATE_WARNING;
fi;

echo "FilesInDir($DIRE/$CHK) ok `date`";
exit $STATE_OK;

