#!/bin/bash
######

MESSAGE=$(cat)
SUBJ="bartlby notify: ${BARTLBY_TRIGGER_SVC_SRV_NAME} / ${BARTLBY_TRIGGER_SVC_NAME} : ${BARTLBY_TRIGGER_SVC_CURRENT_STATE_READABLE} ";
echo -e ${BARTLBY_TRIGGER_SVC_SRV_NAME} $MESSAGE|mail -s "$SUBJ" $BARTLBY_TRIGGER_WRK_EMAIL



