#find git
find_package(Git)
if(GIT_FOUND)
    execute_process(COMMAND ${GIT_EXECUTABLE}  describe --abbrev=4 --always  RESULT_VARIABLE res_var OUTPUT_VARIABLE GIT_COM_ID )
    if( NOT ${res_var} EQUAL 0 )
        set( GIT_VERSION "UNKW")
        message( WARNING "Git failed (not a repo, or no tags). Build will not contain git revision info." )
    endif()
    string( REPLACE "\n" "" GIT_VERSION ${GIT_COM_ID} )
else()
    set( GIT_VERSION  "unknown (git not found!)")
    message( WARNING "Git not found. Build will not contain git revision info." )
endif()
